name: Features | Angular PreTest/Build/Test
on:
  push:
    branches:
      - 'feature'
      - 'feature/**'

  pull_request:
    branches: [feature]

jobs:
  build:
    name: Build project
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Cache node packages
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Setup node ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install project packages
        run: npm install
      - name: Build project to production
        run: npm run build:prod
      - name: ls
        run: ls
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ducatus-dist
          path: ./dist
  zip:
    name: Create project zip
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: ls
        run: ls
      - name: Download artifacts from build
        uses: actions/download-artifact@v2
        with:
          name: ducatus-dist
      - name: ls
        run: ls
      - name: Zip Folder
        run: zip -r -X ducatus-site@feature.zip ducatus-site
      - name: ls
        run: ls
      - uses: actions/upload-artifact@v2
        with:
          name: ducatus-site@feature-zip
          path: ducatus-site@feature.zip
          retention-days: 2
  upload:
    name: Upload artifact
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: ls
        run: ls
      - name: Download artifacts from build
        uses: actions/download-artifact@v2
        with:
          name: ducatus-dist
      - name: ls
        run: ls
      - uses: actions/upload-artifact@v2
        with:
          name: feature-dist
          path: ducatus-site
          retention-days: 1
