name: Features Trigger Manually
on:
  workflow_dispatch:
    inputs:
      version:
        description: Node Version
        default: 12
        required: true
      deploy:
        description: Deploy to test server
        default: true
        required: false
jobs:
  build:
    name: Build project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Cache node packages
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Setup node ${{ github.event.inputs.version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ github.event.inputs.version }}
      - name: Install project packages
        run: npm install
      - name: Build project to production
        run: npm run build:prod
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ducatus-dist
          path: ./dist
          retention-days: 1
  deploy:
    if: ${{ github.event.inputs.deploy == 'true' }}
    name: Deploy project to test server
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts from build
        uses: actions/download-artifact@v2
        with:
          name: ducatus-dist
      - name: Deploying to server
        run: rsync ${{ secrets.DEPLOY_TEST_SWITCHES }} ${{ secrets.DEPLOY_TEST_PATH }} ${{ secrets.DEPLOY_TEST_USER }}:${{ secrets.DEPLOY_TEST_KEY }}@${{ secrets.DEPLOY_TEST_HOST }}:${{ secrets.DEPLOY_TEST_REMOTE_PATH }}
